### ISSUE TITLE
Shopping List.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/advanced_ruby#2]
https://github.com/osifoanosike/advanced_ruby/tree/master/ShoppingList

**Comment by Shruti2791** [comment]
1) Keep separate classes in separate files.
2) Why do we need attr_accessor in both of the classes ?
3) +1 for CartItem class.
4) Extra lines in the eof.

**Comment by osifoanosike** [comment]
1. Class files have been separated.
2. attr_accessor removed from ShoppingList. An instance variable would do.
3. Thanks!
4. Fixed

**Comment by Shruti2791** [comment]
1) Code Comments are always written on the line above that code.
2) Why do we need attr_accessor in CartItem class ? (please answer this in your comment)

**Comment by osifoanosike** [comment]
Comment placement corrected.
I used attr_accessor because i need to access CartItem properties in another class (ShoppingList)

**Comment by osifoanosike** [comment]
I've modified CartItem's accessors to read-only (attr_reader ), because ShoppingList only accesses it and doesn't change it's values.

**Comment by Shruti2791** [comment]
Looks Good

**Comment by osifoanosike** [comment]
Thanks
