### ISSUE TITLE
Interactive Program.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/advanced_ruby#3]
https://github.com/osifoanosike/advanced_ruby/tree/master/InteractiveProgram

**Comment by yuktikhurana** [comment]
here, we need to create something like the ruby IRB.
whenever we enter a blank line it should evaluate the code that we've written. And entering q should quit it.

For e.g
i type line by line
def abc
  puts 'pqr'
end
//i enter blank line and it should evaluate the above code
If you've any doubts with this question, please feel free to ping on skype/gmail(yukti@vinsol.com)

**Comment by osifoanosike** [comment]
Fixed.

**Comment by yuktikhurana** [comment]
1. it's not working as expected.
   Try with the following input
   c = 4
   //blank
   puts c
   //blank
   i get an error.

**Comment by osifoanosike** [comment]
Faulty binding logic corrected.

**Comment by yuktikhurana** [comment]
Good work :)
