### ISSUE TITLE
Singleton Method.

### ISSUE THREAD

**Issue by osifoanosike** [osifoanosike/advanced_ruby#4]
https://github.com/osifoanosike/advanced_ruby/tree/master/SingletonMethod

**Comment by abhishekjain16** [comment]
Good. But now We would like you to try one more method for doing the same: class << self
Try doing the same using above

**Comment by osifoanosike** [comment]
Done

**Comment by osifoanosike** [comment]
Also i'd love to ask which is more common between  using the class << self in the parent class and using:
class << obj
  def my_singleton_method
    ...
  end
end.
Thanks

**Comment by abhishekjain16** [comment]
It's developers choice. There is nothing wrong in any.

**Comment by osifoanosike** [comment]
okay thanks
